### PR TITLE
fix: Support different query parameter names in search

### LINKED ISSUE #40: Cannot search for books or authors with KOReader
I noticed the following error when using KOReader to access the OPDS feed.

It shows me the option to search the OPDS library, but fails with an exception in Jellyfin.

According to my reverse proxy, the request looks like this:

```text
"HEAD /opds/search?query=stuff HTTP/1.1" 405
"GET /opds/search?query=stuff HTTP/1.1" 400
```

405 and 400 are the return codes.

Here's the exception that I get from Jellyfin:

```text
jellyfin  | [07:18:02] [ERR] [30] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /opds/search.
jellyfin  | System.ArgumentNullException: Value cannot be null. (Parameter 'searchTerm')
jellyfin  |    at System.ArgumentNullException.Throw(String paramName)
jellyfin  |    at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
jellyfin  |    at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
jellyfin  |    at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
jellyfin  |    at Emby.Server.Implementations.Library.SearchEngine.GetSearchHints(SearchQuery query, User user)
jellyfin  |    at Emby.Server.Implementations.Library.SearchEngine.GetSearchHints(SearchQuery query)
jellyfin  |    at Jellyfin.Plugin.Opds.Services.OpdsFeedProvider.SearchBooks(String baseUrl, Guid userId, String searchTerm)
jellyfin  |    at Jellyfin.Plugin.Opds.OpdsApi.SearchBookFromQuery(String searchTerms)
jellyfin  |    at lambda_method2365(Closure, Object)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin  |    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin  |    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin  |    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin  |    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfin  |    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin  |    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

It looks like the query parameter does not have the expected name `searchTerm`. Seeing as KOReader works perfectly well with other OPDS sources, I suspect that it's a bug in this plugin.

----

Thanks for all the hard work. I'll see if I can turn up some more information once I get to a real PC. 🙂

### PR DESCRIPTION
**Pull request by rluetzner**
This fixes an issue that easily reproducible with KOReader, but might affect other OPDS clients too.

Until now, we expected the client to define a `searchTerms` query parameter. However, according to the OPDS spec at

https://specs.opds.io/opds-1.2#3-search

the query parameter should actually be called `q` instead. Even more confusing is, that KOReader uses `query`.

For backwards compatibility reasons we keep `searchTerms` and add the other two options as well. All parameters are optional, so we need to check which one we got.

There is one small caveat to this implementation. When, for example, I run a search without search terms against Project Gutenberg's OPDS endpoint, I get back the entire catalog.

However, because we cannot set the default value of the optional parameters to `null`, we cannot determine if any or none of the options were used.

I ultimately decided to return a 400 Bad Request instead, in case the `searchTerms` ends up empty. This will ensure that we will detect issues with other OPDS clients in the future, in case there are implementations out there that use _yet another_ parameter name for the search terms.

If we instead processed the request as empty by default, a client that uses a different query parameter name would just have the entire catalog returned. Users would be confused why their filters did not work and the underlying issue might be hard to track down.

This fixes #40.

### CODE REVIEW

**Comment by rluetzner** [comment]
I tested this by building a new DLL and replacing the plugin on my productive Jellyfin instance. The fix works as expected and I was able to search for books by their title. :slightly_smiling_face: 

According to the OPDS specs, there are additional query parameters to, e.g. search for authors instead (or in addition to a title). This would be easy to add and might be something for the future. Sadly, at least KOReader does not support searching for an author directly, so I don't have an OPDS client at hand to test such a change anyway.

**Comment by crobibero** [comment]
Huh I was pretty sure that I originally tested with KOReader 🤷 

Here is a patch that sets the default parameter to null

```
Index: Jellyfin.Plugin.Opds/OpdsApi.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Jellyfin.Plugin.Opds/OpdsApi.cs b/Jellyfin.Plugin.Opds/OpdsApi.cs
--- a/Jellyfin.Plugin.Opds/OpdsApi.cs	(revision 3928bbc093bbda8d0912d4adb600ea1e56e6b1eb)
+++ b/Jellyfin.Plugin.Opds/OpdsApi.cs	(date 1715693482237)
@@ -215,14 +215,25 @@
     /// <summary>
     /// Gets the search result.
     /// </summary>
-    /// <param name="searchTerms">The search terms.</param>
+    /// <param name="searchTerms">The search terms as historically used by this plugin.</param>
+    /// <param name="q">The search terms as defined by the OPDS spec.</param>
+    /// <param name="query">The search terms as some OPDS clients provide them.</param>
     /// <returns>The search feed xml.</returns>
     [HttpGet("Search")]
     [ProducesResponseType(StatusCodes.Status200OK)]
-    public async Task<ActionResult> SearchBookFromQuery([FromQuery] string searchTerms)
+    public async Task<ActionResult> SearchBookFromQuery(
+        [FromQuery] string? searchTerms = null,
+        [FromQuery] string? q = null,
+        [FromQuery] string? query = null)
     {
         try
         {
+            searchTerms ??= q ?? query;
+            if (string.IsNullOrEmpty(searchTerms))
+            {
+                return BadRequest();
+            }
+
             var userId = await AuthorizeAsync().ConfigureAwait(false);
             var feeds = _opdsFeedProvider.SearchBooks(Request.PathBase, userId, searchTerms);
             return BuildOutput(feeds);
```

**Comment by rluetzner** [comment]
Nice. I'm not in reach of a PC right now, but I'll work in the patch later. That's way better. 🙂

**Comment by rluetzner** [comment]
Done. I also replaced

```csharp
           if (string.IsNullOrEmpty(searchTerms))
           {
               return BadRequest();
           }
```

with

```csharp
           if (searchTerms == null)
           {
               return BadRequest();
           }
```

instead, which is more correct. If one of the query parameters was given as an empty string, we can just return the entire catalog, which lines up with how e.g. Project Gutenberg behaves when running a search without a filter.

**Review by crobibero — APPROVED** [review]

**Pull request merged**
